import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'pt' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.academy': 'Academy',
    'nav.professors': 'Professeurs',
    'nav.shop': 'Boutique',
    'nav.myPurchases': 'Mes Achats',
    'nav.favorites': 'Favoris',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.account': 'Compte',
    'nav.cart': 'Panier',
    'nav.signOut': 'Déconnexion',
    'nav.signIn': 'Connexion',
    'nav.getStarted': 'S\'inscrire',

    'landing.hero.badge': 'Progressez dans la Danse avec des Professeurs de Classe Mondiale',
    'landing.hero.titleStart': 'Votre Voyage vers',
    'landing.hero.titleHighlight': 'l\'Excellence en Danse',
    'landing.hero.description': 'Développez votre potentiel avec des cours vidéo structurés et des programmes adaptés à tous les niveaux. Apprenez à votre rythme, n\'importe quand, n\'importe où.',
    'landing.hero.ctaPrimary': 'Commencer à Apprendre',
    'landing.hero.ctaSecondary': 'Explorer l\'Academy',
    'landing.features.titleStart': 'Pourquoi rejoindre',
    'landing.features.titleHighlight': 'NEXA UNIVERSE',
    'landing.features.subtitle': 'Transformez votre parcours de danse avec notre plateforme complète',
    'landing.features.feature1.title': 'Tout au même endroit',
    'landing.features.feature1.description': 'Cours en ligne, programmes de professeurs, contenus exclusifs : tout ton apprentissage est centralisé dans une seule plateforme, simple et organisée. Moins de dispersion. Plus de progression.',
    'landing.features.feature2.title': 'Gestion facile des pass & événements',
    'landing.features.feature2.description': 'Achète tes pass directement sur la plateforme et retrouve-les à tout moment dans ton espace personnel (QR codes, infos, historique). Tes pass, toujours accessibles, toujours prêts.',
    'landing.features.feature3.title': 'Boutique officielle NEXA',
    'landing.features.feature3.description': 'Merch, sac du festivalier, produits utiles pour les danseurs : la boutique NEXA est intégrée à l\'application, avec des avantages réservés aux membres. La culture danse, jusque dans les détails.',
    'landing.cta.badge': 'Offre à Durée Limitée',
    'landing.cta.title': 'Prêt à Commencer Votre Voyage ?',
    'landing.cta.description': 'Rejoignez notre communauté de danseurs passionnés et développez vos compétences dès aujourd\'hui.',
    'landing.cta.pricePrefix': 'À partir de',
    'landing.cta.priceSuffix': '/mois',
    'landing.cta.button': 'Commencer Maintenant',
    'landing.footer.copyright': '© 2024 NEXA UNIVERSE. Tous droits réservés.',

    'academy.header.title': 'Academy',
    'academy.header.accessFull': 'Accès complet à tous les niveaux',
    'academy.header.accessLimited': 'Abonnez-vous pour débloquer tout le contenu',
    'academy.banner.title': 'NEXA UNIVERSE Access',
    'academy.banner.description': 'Créez un compte gratuit pour explorer la plateforme. Passez à NEXA Access pour débloquer tous les contenus premium, des réductions exclusives et bien plus encore.',
    'academy.banner.pricing': 'Abonnement premium : 8.99€/mois ou 89€/an',
    'academy.banner.button': 'Découvrir NEXA Access',
    'academy.filters.title': 'Recherche et filtres',
    'academy.filters.searchPlaceholder': 'Rechercher des vidéos ou programmes...',
    'academy.filters.allProfessors': 'Tous les professeurs',
    'academy.filters.allLevels': 'Tous',
    'academy.filters.beginner': 'Débutant',
    'academy.filters.intermediate': 'Inter',
    'academy.filters.advanced': 'Avancé',
    'academy.filters.activeLabel': 'Filtres actifs:',
    'academy.filters.resetAll': 'Réinitialiser tout',
    'academy.tabs.programs': 'Programmes',
    'academy.tabs.videos': 'Vidéos',
    'academy.empty.programsFiltered': 'Aucun programme ne correspond à vos filtres',
    'academy.empty.programsNone': 'Aucun programme disponible pour le moment',
    'academy.empty.videosFiltered': 'Aucune vidéo ne correspond à vos filtres',
    'academy.empty.videosNone': 'Aucune vidéo disponible',
    'academy.card.locked': 'Verrouillé',
    'academy.card.accessible': 'Accessible',
    'academy.card.purchased': 'Acheté',
    'academy.card.by': 'Par',
    'academy.card.videos': 'vidéos',
    'academy.card.minutes': 'min',
    'academy.card.public': 'Public',
    'academy.card.subscribers': 'Abonnés',
    'academy.card.paid': 'Payant',
    'academy.card.free': 'Gratuit',
    'academy.card.loginRequired': 'Connexion requise',
    'academy.card.subscriptionRequired': 'Abonnement requis',
    'academy.levels.beginner': 'Débutant',
    'academy.levels.intermediate': 'Intermédiaire',
    'academy.levels.advanced': 'Avancé',
    'academy.levels.allLevels': 'Tous niveaux',
    'academy.modal.locked': 'Vidéo verrouillée',
    'academy.modal.loginMessage': 'Connectez-vous pour accéder à cette vidéo',
    'academy.modal.login': 'Se connecter',
    'academy.modal.subscribeProfessor': 'Abonnez-vous au professeur pour accéder à cette vidéo',
    'academy.modal.viewProfessor': 'Voir le profil du professeur',
    'academy.modal.subscribeNexa': 'Abonnez-vous à NEXA Access pour débloquer cette vidéo',
    'academy.modal.subscribeButton': 'S\'abonner à NEXA Access',
    'academy.modal.close': 'Fermer',

    'professors.header.titleStart': 'Rencontrez Vos',
    'professors.header.titleHighlight': 'Instructeurs',
    'professors.header.subtitle': 'Apprenez auprès de professionnels de kizomba de classe mondiale avec des années d\'expérience pédagogique',
    'professors.search.placeholder': 'Rechercher un professeur par nom ou bio...',
    'professors.filters.allSpecialties': 'Toutes spécialités',
    'professors.filters.activeLabel': 'Filtres actifs:',
    'professors.filters.resetAll': 'Réinitialiser tout',
    'professors.empty.filtered': 'Aucun professeur ne correspond à vos filtres',
    'professors.empty.none': 'Aucun professeur disponible pour le moment',
    'professors.card.featured': 'Instructeur Vedette',
    'professors.card.founder': 'Instructeur Fondateur',
    'professors.card.experience': 'ans d\'expérience',
    'professors.card.noBio': 'Aucune biographie disponible.',
    'professors.card.watchIntro': 'Regarder l\'Introduction',
    'professors.card.viewProfile': 'Voir le Profil & Cours',

    'shop.header.brand': 'NEXA UNIVERSE',
    'shop.header.title': 'Shop',
    'shop.header.subtitle': 'Marchandises exclusives et pass événements',
    'shop.header.memberActive': 'Prix membre actif',
    'shop.success.addedToCart': 'ajouté au panier !',
    'shop.success.viewCart': 'Voir le Panier',
    'shop.search.placeholder': 'Rechercher des produits...',
    'shop.filters.priceLabel': 'Prix:',
    'shop.filters.all': 'Tous',
    'shop.filters.under25': 'Moins de 25€',
    'shop.filters.range25to50': '25€ - 50€',
    'shop.filters.over50': 'Plus de 50€',
    'shop.tabs.merchandise': 'Merchandise',
    'shop.tabs.events': 'Events',
    'shop.empty.filtered': 'Aucun produit ne correspond à votre recherche',
    'shop.empty.no': 'Aucun',
    'shop.empty.product': 'produit',
    'shop.empty.event': 'événement',
    'shop.empty.available': 'disponible pour le moment',
    'shop.product.memberBadge': 'PRIX MEMBRE',
    'shop.product.outOfStock': 'Rupture de Stock',
    'shop.product.eventPass': 'Pass Événement',
    'shop.product.availableSizes': 'Tailles disponibles:',
    'shop.product.availableCategories': 'Catégories disponibles:',
    'shop.product.forMembers': 'pour les membres',
    'shop.product.addToCart': 'Ajouter au Panier',
    'shop.modal.selectSize': 'Sélectionner la Taille',
    'shop.modal.selectCategory': 'Sélectionnez une catégorie',
    'shop.modal.quantity': 'Quantité',
    'shop.modal.cancel': 'Annuler',

    'cart.notSignedIn.message': 'Connectez-vous pour voir votre panier',
    'cart.notSignedIn.button': 'Se Connecter',
    'cart.success.title': 'Commande Passée avec Succès !',
    'cart.success.message': 'Merci pour votre commande. Nous vous enverrons un email de confirmation sous peu.',
    'cart.success.continueShopping': 'Continuer les Achats',
    'cart.success.viewOrders': 'Voir les Commandes',
    'cart.header.your': 'Votre',
    'cart.header.cart': 'Panier',
    'cart.empty.title': 'Votre panier est vide',
    'cart.empty.message': 'Ajoutez des articles pour commencer',
    'cart.empty.button': 'Aller à la Boutique',
    'cart.item.category': 'Catégorie',
    'cart.item.size': 'Taille',
    'cart.item.subtotal': 'Sous-total',
    'cart.summary.title': 'Résumé de Commande',
    'cart.summary.subtotal': 'Sous-total',
    'cart.summary.memberSavings': 'Économies Membre',
    'cart.summary.total': 'Total',
    'cart.summary.fullName': 'Nom Complet *',
    'cart.summary.email': 'Email *',
    'cart.summary.phone': 'Téléphone',
    'cart.summary.shippingAddress': 'Adresse de Livraison *',
    'cart.summary.orderNotes': 'Notes de commande (optionnel)',
    'cart.summary.processing': 'Traitement...',
    'cart.summary.placeOrder': 'Passer Commande',
    'cart.summary.manualNote': 'Votre commande sera traitée manuellement. Nous vous contacterons pour les détails de paiement.',
    'cart.errors.empty': 'Votre panier est vide',
    'cart.errors.shippingRequired': 'Veuillez remplir toutes les informations de livraison',

    'favorites.header.my': 'Mes',
    'favorites.header.favorites': 'Favoris',
    'favorites.header.savedSingular': 'favori enregistré',
    'favorites.header.savedPlural': 'favoris enregistrés',
    'favorites.tabs.all': 'Tous',
    'favorites.tabs.professors': 'Professeurs',
    'favorites.tabs.videos': 'Vidéos',
    'favorites.tabs.programs': 'Programmes',
    'favorites.empty.title': 'Aucun favori',
    'favorites.empty.message': 'Commencez à ajouter des professeurs, vidéos et programmes à vos favoris',
    'favorites.empty.button': 'Explorer l\'Academy',
    'favorites.sections.professors': 'Professeurs',
    'favorites.sections.videos': 'Vidéos',
    'favorites.sections.programs': 'Programmes',
    'favorites.cards.viewProfile': 'Voir le profil',
    'favorites.cards.removeTitle': 'Retirer des favoris',
    'favorites.cards.watch': 'Regarder',
    'favorites.cards.viewProgram': 'Voir le programme',
    'favorites.cards.videos': 'vidéos',

    'account.header.title': 'Paramètres du Compte',
    'account.tabs.profile': 'Profil',
    'account.tabs.subscription': 'Abonnements',
    'account.tabs.billing': 'Facturation',
    'account.profile.title': 'Informations du Profil',
    'account.profile.email': 'Email',
    'account.profile.fullName': 'Nom Complet',
    'account.profile.role': 'Rôle',
    'account.profile.errorUpdate': 'Erreur lors de la mise à jour du profil',
    'account.profile.successUpdate': 'Profil mis à jour avec succès',
    'account.profile.saving': 'Enregistrement...',
    'account.profile.saveButton': 'Enregistrer les Modifications',
    'account.subscription.title': 'Mes Abonnements',
    'account.subscription.platformTitle': 'Abonnement Plateforme',
    'account.subscription.active': 'Actif',
    'account.subscription.inactive': 'Inactif',
    'account.subscription.expiresOn': 'Expire le',
    'account.subscription.benefit1': 'Accès aux vidéos dont la plateforme est propriétaire',
    'account.subscription.benefit2': 'Réduction dans la boutique',
    'account.subscription.benefit3': 'Réduction sur les pass des événements partenaires',
    'account.subscription.platformRequired': 'L\'abonnement plateforme est requis pour accéder à l\'académie et s\'abonner aux professeurs.',
    'account.subscription.modal.chooseYourPlan': 'Choisissez votre abonnement',
    'account.subscription.modal.accessAllPremium': 'Accédez à tous les contenus premium de la plateforme',
    'account.subscription.modal.monthly': 'Mensuel',
    'account.subscription.modal.flexibleCommitment': 'Engagement flexible',
    'account.subscription.modal.perMonth': '/mois',
    'account.subscription.modal.annual': 'Annuel',
    'account.subscription.modal.bestOffer': 'Meilleure offre',
    'account.subscription.modal.perYear': '/an',
    'account.subscription.modal.orPerMonth': 'Soit {price}€/mois',
    'account.subscription.modal.savePercent': 'ÉCONOMISEZ {percent}%',
    'account.subscription.modal.chooseMonthly': 'Choisir Mensuel',
    'account.subscription.modal.chooseAnnual': 'Choisir Annuel',
    'account.subscription.modal.securePayment': 'Paiement sécurisé par Stripe • Annulation à tout moment',
    'account.subscription.modal.benefit1': 'Accès aux vidéos dont la plateforme est propriétaire',
    'account.subscription.modal.benefit2': 'Réduction dans la boutique',
    'account.subscription.modal.benefit3': 'Réduction sur les pass des événements partenaires',
    'account.subscription.professorsTitle': 'Abonnements Professeurs',
    'account.subscription.subscribedTo': 'Vous êtes abonné à',
    'account.subscription.professorSingular': 'professeur',
    'account.subscription.professorPlural': 'professeurs',
    'account.subscription.noProfessors': 'Aucun abonnement professeur actif',
    'account.subscription.activeSubscription': 'Abonnement actif',
    'account.subscription.discountMessage': 'Vous bénéficiez de',
    'account.subscription.discountSuffix': 'de réduction sur tous les programmes payants de ce professeur',
    'account.subscription.discoverMore': 'Découvrir d\'autres professeurs',
    'account.subscription.subscribeBenefitsIntro': 'Abonnez-vous à vos professeurs préférés pour :',
    'account.subscription.subscribeBenefit1': 'Accès à tous leurs contenus exclusifs (vidéos et programmes)',
    'account.subscription.subscribeBenefit2': 'Réductions sur les programmes payants',
    'account.subscription.subscribeBenefit3': 'Priorité de réservation pour les événements',
    'account.subscription.discoverProfessors': 'Découvrir les professeurs',
    'account.subscription.subscribeToPlatform': 'S\'abonner à la Plateforme',
    'account.subscription.cancelSubscription': 'Résilier l\'Abonnement',
    'account.subscription.cancelProfessorSubscription': 'Résilier l\'Abonnement',
    'account.subscription.cancelModalTitle': 'Confirmer la Résiliation',
    'account.subscription.cancelPlatformMessage': 'Êtes-vous sûr de vouloir résilier votre abonnement à la plateforme ? Vous perdrez l\'accès à tous les contenus.',
    'account.subscription.cancelProfessorMessage': 'Êtes-vous sûr de vouloir résilier votre abonnement à {{name}} ? Vous perdrez l\'accès aux contenus exclusifs de ce professeur.',
    'account.subscription.cancellationPolicy': 'Politique de Résiliation',
    'account.subscription.policyPoint1': 'Votre abonnement restera actif jusqu\'à la fin de la période payée',
    'account.subscription.policyPoint2': 'Aucun remboursement ne sera effectué pour le temps restant',
    'account.subscription.policyPoint3': 'Vous pourrez vous réabonner à tout moment',
    'account.subscription.keepSubscription': 'Conserver',
    'account.subscription.confirmCancel': 'Confirmer',
    'account.subscription.cancelling': 'Résiliation...',
    'account.subscription.platformCancelSuccess': 'Abonnement plateforme résilié avec succès',
    'account.subscription.professorCancelSuccess': 'Abonnement professeur résilié avec succès',
    'account.subscription.cancelError': 'Erreur lors de la résiliation',
    'account.billing.title': 'Informations de Facturation',
    'account.billing.paymentMethod': 'Méthode de Paiement',
    'account.billing.stripeMessage': 'Connectez Stripe pour gérer la facturation et les méthodes de paiement',
    'account.billing.stripeRequired': 'Intégration Stripe Requise',
    'account.billing.history': 'Historique de Facturation',
    'account.billing.noHistory': 'Aucun historique de facturation disponible',

    'signin.header.title': 'Bon Retour',
    'signin.header.subtitle': 'Accédez à votre espace personnel',
    'signin.form.email': 'Email',
    'signin.form.emailPlaceholder': 'votre@email.com',
    'signin.form.password': 'Mot de passe',
    'signin.form.passwordPlaceholder': 'Entrez votre mot de passe',
    'signin.form.signingIn': 'Connexion...',
    'signin.form.signIn': 'Se Connecter',
    'signin.footer.noAccount': 'Pas encore de compte ?',
    'signin.footer.signUp': 'S\'inscrire',

    'signup.header.title': 'Commencez Votre Voyage',
    'signup.header.subtitle': 'Rejoignez NEXA Universe dès aujourd\'hui',
    'signup.form.fullName': 'Nom Complet',
    'signup.form.fullNamePlaceholder': 'Votre nom',
    'signup.form.email': 'Email',
    'signup.form.emailPlaceholder': 'votre@email.com',
    'signup.form.password': 'Mot de passe',
    'signup.form.passwordPlaceholder': 'Au moins 6 caractères',
    'signup.form.creating': 'Création du compte...',
    'signup.form.success': 'Succès !',
    'signup.form.createAccount': 'Créer un Compte',
    'signup.form.successMessage': 'Compte créé avec succès !',
    'signup.errors.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    'signup.footer.hasAccount': 'Vous avez déjà un compte ?',
    'signup.footer.signIn': 'Se connecter',

    'purchases.title': 'Mes Achats',
    'purchases.subtitle': 'Gérez vos abonnements et vos achats',
    'purchases.platformSubscription': 'Abonnement Plateforme',
    'purchases.status.active': 'Actif',
    'purchases.status.trial': 'Essai',
    'purchases.status.inactive': 'Inactif',
    'purchases.status.cancelled': 'Annulé',
    'purchases.status.accessible': 'Accessible',
    'purchases.status.refunded': 'Remboursé',
    'purchases.status.expired': 'Expiré',
    'purchases.expiresOn': 'Expire le',
    'purchases.expiresSoon': 'Votre abonnement expire bientôt',
    'purchases.since': 'Depuis le',
    'purchases.purchasedOn': 'Acheté le',
    'purchases.viewProfile': 'Voir le profil',
    'purchases.watch': 'Regarder',
    'purchases.access': 'Accéder',

    'purchases.tabs.professors': 'Professeurs',
    'purchases.tabs.programs': 'Programmes',
    'purchases.tabs.videos': 'Vidéos',
    'purchases.tabs.orders': 'Commandes',

    'purchases.noProfessors': 'Aucun abonnement professeur',
    'purchases.noProfessorsDesc': 'Abonnez-vous à vos professeurs préférés pour accéder à leur contenu exclusif',
    'purchases.discoverProfessors': 'Découvrir les professeurs',

    'purchases.noPrograms': 'Aucun programme acheté',
    'purchases.noProgramsDesc': 'Achetez des programmes complets pour progresser efficacement',
    'purchases.explorePrograms': 'Explorer les programmes',

    'purchases.noVideos': 'Aucune vidéo achetée',
    'purchases.noVideosDesc': 'Achetez des vidéos individuelles pour enrichir votre apprentissage',
    'purchases.exploreAcademy': 'Explorer l\'académie',

    'purchases.noOrders': 'Aucune commande',
    'purchases.noOrdersDesc': 'Commandez des produits dans notre boutique',
    'purchases.visitShop': 'Visiter la boutique',

    'purchases.order': 'Commande',
    'purchases.items': 'Articles',
    'purchases.memberPrice': 'Prix membre',
    'purchases.delivered': 'Livrée',
    'purchases.shipped': 'Expédiée',
    'purchases.processing': 'En traitement',
    'purchases.paid': 'Payée',
    'purchases.pending': 'En attente',

    'common.level.beginner': 'Débutant',
    'common.level.intermediate': 'Intermédiaire',
    'common.level.advanced': 'Avancé',
    'common.minutes': 'min',
    'common.videos': 'vidéos',
    'common.video': 'vidéo',
  },
  en: {
    'nav.academy': 'Academy',
    'nav.professors': 'Professors',
    'nav.shop': 'Shop',
    'nav.myPurchases': 'My Purchases',
    'nav.favorites': 'Favorites',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.account': 'Account',
    'nav.cart': 'Cart',
    'nav.signOut': 'Sign Out',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',

    'landing.hero.badge': 'Progress in Dance with World-Class Teachers',
    'landing.hero.titleStart': 'Your Journey to',
    'landing.hero.titleHighlight': 'Dance Excellence',
    'landing.hero.description': 'Develop your potential with structured video courses and programs adapted to all levels. Learn at your own pace, anytime, anywhere.',
    'landing.hero.ctaPrimary': 'Start Learning Now',
    'landing.hero.ctaSecondary': 'Explore Academy',
    'landing.features.titleStart': 'Why join',
    'landing.features.titleHighlight': 'NEXA UNIVERSE',
    'landing.features.subtitle': 'Transform your dance journey with our comprehensive platform',
    'landing.features.feature1.title': 'Everything in one place',
    'landing.features.feature1.description': 'Online courses, professor programs, exclusive content: all your learning is centralized in a single, simple and organized platform. Less distraction. More progress.',
    'landing.features.feature2.title': 'Easy pass & event management',
    'landing.features.feature2.description': 'Buy your passes directly on the platform and access them anytime in your personal space (QR codes, info, history). Your passes, always accessible, always ready.',
    'landing.features.feature3.title': 'Official NEXA Shop',
    'landing.features.feature3.description': 'Merch, festival bags, useful products for dancers: the NEXA shop is integrated into the app, with exclusive benefits for members. Dance culture, down to the details.',
    'landing.cta.badge': 'Limited Time Offer',
    'landing.cta.title': 'Ready to Begin Your Journey?',
    'landing.cta.description': 'Join our community of passionate dancers and develop your skills today.',
    'landing.cta.pricePrefix': 'From just',
    'landing.cta.priceSuffix': '/month',
    'landing.cta.button': 'Get Started Now',
    'landing.footer.copyright': '© 2024 NEXA UNIVERSE. All rights reserved.',

    'academy.header.title': 'Academy',
    'academy.header.accessFull': 'Full access to all levels',
    'academy.header.accessLimited': 'Subscribe to unlock all content',
    'academy.banner.title': 'NEXA UNIVERSE Access',
    'academy.banner.description': 'Create a free account to explore the platform. Upgrade to NEXA Access to unlock all premium content, exclusive discounts and much more.',
    'academy.banner.pricing': 'Premium subscription: €8.99/month or €89/year',
    'academy.banner.button': 'Discover NEXA Access',
    'academy.filters.title': 'Search and filters',
    'academy.filters.searchPlaceholder': 'Search for videos or programs...',
    'academy.filters.allProfessors': 'All professors',
    'academy.filters.allLevels': 'All',
    'academy.filters.beginner': 'Beginner',
    'academy.filters.intermediate': 'Inter',
    'academy.filters.advanced': 'Advanced',
    'academy.filters.activeLabel': 'Active filters:',
    'academy.filters.resetAll': 'Reset all',
    'academy.tabs.programs': 'Programs',
    'academy.tabs.videos': 'Videos',
    'academy.empty.programsFiltered': 'No programs match your filters',
    'academy.empty.programsNone': 'No programs available at the moment',
    'academy.empty.videosFiltered': 'No videos match your filters',
    'academy.empty.videosNone': 'No videos available',
    'academy.card.locked': 'Locked',
    'academy.card.accessible': 'Accessible',
    'academy.card.purchased': 'Purchased',
    'academy.card.by': 'By',
    'academy.card.videos': 'videos',
    'academy.card.minutes': 'min',
    'academy.card.public': 'Public',
    'academy.card.subscribers': 'Subscribers',
    'academy.card.paid': 'Paid',
    'academy.card.free': 'Free',
    'academy.card.loginRequired': 'Login required',
    'academy.card.subscriptionRequired': 'Subscription required',
    'academy.levels.beginner': 'Beginner',
    'academy.levels.intermediate': 'Intermediate',
    'academy.levels.advanced': 'Advanced',
    'academy.levels.allLevels': 'All levels',
    'academy.modal.locked': 'Locked Video',
    'academy.modal.loginMessage': 'Sign in to access this video',
    'academy.modal.login': 'Sign In',
    'academy.modal.subscribeProfessor': 'Subscribe to the professor to access this video',
    'academy.modal.viewProfessor': 'View professor profile',
    'academy.modal.subscribeNexa': 'Subscribe to NEXA Access to unlock this video',
    'academy.modal.subscribeButton': 'Subscribe to NEXA Access',
    'academy.modal.close': 'Close',

    'professors.header.titleStart': 'Meet Your',
    'professors.header.titleHighlight': 'Instructors',
    'professors.header.subtitle': 'Learn from world-class kizomba professionals with years of teaching experience',
    'professors.search.placeholder': 'Search professor by name or bio...',
    'professors.filters.allSpecialties': 'All specialties',
    'professors.filters.activeLabel': 'Active filters:',
    'professors.filters.resetAll': 'Reset all',
    'professors.empty.filtered': 'No professors match your filters',
    'professors.empty.none': 'No professors available at the moment',
    'professors.card.featured': 'Featured Instructor',
    'professors.card.founder': 'Founding Instructor',
    'professors.card.experience': 'years experience',
    'professors.card.noBio': 'No biography available.',
    'professors.card.watchIntro': 'Watch Introduction',
    'professors.card.viewProfile': 'View Profile & Courses',

    'shop.header.brand': 'NEXA UNIVERSE',
    'shop.header.title': 'Shop',
    'shop.header.subtitle': 'Exclusive merchandise and event passes',
    'shop.header.memberActive': 'Member pricing active',
    'shop.success.addedToCart': 'added to cart!',
    'shop.success.viewCart': 'View Cart',
    'shop.search.placeholder': 'Search products...',
    'shop.filters.priceLabel': 'Price:',
    'shop.filters.all': 'All',
    'shop.filters.under25': 'Under €25',
    'shop.filters.range25to50': '€25 - €50',
    'shop.filters.over50': 'Over €50',
    'shop.tabs.merchandise': 'Merchandise',
    'shop.tabs.events': 'Events',
    'shop.empty.filtered': 'No products match your search',
    'shop.empty.no': 'No',
    'shop.empty.product': 'product',
    'shop.empty.event': 'event',
    'shop.empty.available': 'available at the moment',
    'shop.product.memberBadge': 'MEMBER PRICE',
    'shop.product.outOfStock': 'Out of Stock',
    'shop.product.eventPass': 'Event Pass',
    'shop.product.availableSizes': 'Available sizes:',
    'shop.product.availableCategories': 'Available categories:',
    'shop.product.forMembers': 'for members',
    'shop.product.addToCart': 'Add to Cart',
    'shop.modal.selectSize': 'Select Size',
    'shop.modal.selectCategory': 'Select a category',
    'shop.modal.quantity': 'Quantity',
    'shop.modal.cancel': 'Cancel',

    'cart.notSignedIn.message': 'Sign in to view your cart',
    'cart.notSignedIn.button': 'Sign In',
    'cart.success.title': 'Order Placed Successfully!',
    'cart.success.message': 'Thank you for your order. We\'ll send you a confirmation email shortly.',
    'cart.success.continueShopping': 'Continue Shopping',
    'cart.success.viewOrders': 'View Orders',
    'cart.header.your': 'Your',
    'cart.header.cart': 'Cart',
    'cart.empty.title': 'Your cart is empty',
    'cart.empty.message': 'Add some items to get started',
    'cart.empty.button': 'Go to Shop',
    'cart.item.category': 'Category',
    'cart.item.size': 'Size',
    'cart.item.subtotal': 'Subtotal',
    'cart.summary.title': 'Order Summary',
    'cart.summary.subtotal': 'Subtotal',
    'cart.summary.memberSavings': 'Member Savings',
    'cart.summary.total': 'Total',
    'cart.summary.fullName': 'Full Name *',
    'cart.summary.email': 'Email *',
    'cart.summary.phone': 'Phone',
    'cart.summary.shippingAddress': 'Shipping Address *',
    'cart.summary.orderNotes': 'Order notes (optional)',
    'cart.summary.processing': 'Processing...',
    'cart.summary.placeOrder': 'Place Order',
    'cart.summary.manualNote': 'Your order will be processed manually. We\'ll contact you for payment details.',
    'cart.errors.empty': 'Your cart is empty',
    'cart.errors.shippingRequired': 'Please fill in all shipping information',

    'favorites.header.my': 'My',
    'favorites.header.favorites': 'Favorites',
    'favorites.header.savedSingular': 'saved favorite',
    'favorites.header.savedPlural': 'saved favorites',
    'favorites.tabs.all': 'All',
    'favorites.tabs.professors': 'Professors',
    'favorites.tabs.videos': 'Videos',
    'favorites.tabs.programs': 'Programs',
    'favorites.empty.title': 'No favorites',
    'favorites.empty.message': 'Start adding professors, videos and programs to your favorites',
    'favorites.empty.button': 'Explore Academy',
    'favorites.sections.professors': 'Professors',
    'favorites.sections.videos': 'Videos',
    'favorites.sections.programs': 'Programs',
    'favorites.cards.viewProfile': 'View profile',
    'favorites.cards.removeTitle': 'Remove from favorites',
    'favorites.cards.watch': 'Watch',
    'favorites.cards.viewProgram': 'View program',
    'favorites.cards.videos': 'videos',

    'account.header.title': 'Account Settings',
    'account.tabs.profile': 'Profile',
    'account.tabs.subscription': 'Subscription',
    'account.tabs.billing': 'Billing',
    'account.profile.title': 'Profile Information',
    'account.profile.email': 'Email',
    'account.profile.fullName': 'Full Name',
    'account.profile.role': 'Role',
    'account.profile.errorUpdate': 'Error updating profile',
    'account.profile.successUpdate': 'Profile updated successfully',
    'account.profile.saving': 'Saving...',
    'account.profile.saveButton': 'Save Changes',
    'account.subscription.title': 'My Subscriptions',
    'account.subscription.platformTitle': 'Platform Subscription',
    'account.subscription.active': 'Active',
    'account.subscription.inactive': 'Inactive',
    'account.subscription.expiresOn': 'Expires on',
    'account.subscription.benefit1': 'Access to platform-owned videos',
    'account.subscription.benefit2': 'Discount in the shop',
    'account.subscription.benefit3': 'Discount on partner event passes',
    'account.subscription.platformRequired': 'Platform subscription is required to access the academy and subscribe to professors.',
    'account.subscription.modal.chooseYourPlan': 'Choose your subscription',
    'account.subscription.modal.accessAllPremium': 'Access all premium platform content',
    'account.subscription.modal.monthly': 'Monthly',
    'account.subscription.modal.flexibleCommitment': 'Flexible commitment',
    'account.subscription.modal.perMonth': '/month',
    'account.subscription.modal.annual': 'Annual',
    'account.subscription.modal.bestOffer': 'Best offer',
    'account.subscription.modal.perYear': '/year',
    'account.subscription.modal.orPerMonth': 'Or {price}€/month',
    'account.subscription.modal.savePercent': 'SAVE {percent}%',
    'account.subscription.modal.chooseMonthly': 'Choose Monthly',
    'account.subscription.modal.chooseAnnual': 'Choose Annual',
    'account.subscription.modal.securePayment': 'Secure payment by Stripe • Cancel anytime',
    'account.subscription.modal.benefit1': 'Access to platform-owned videos',
    'account.subscription.modal.benefit2': 'Discount in the shop',
    'account.subscription.modal.benefit3': 'Discount on partner event passes',
    'account.subscription.professorsTitle': 'Professor Subscriptions',
    'account.subscription.subscribedTo': 'You are subscribed to',
    'account.subscription.professorSingular': 'professor',
    'account.subscription.professorPlural': 'professors',
    'account.subscription.noProfessors': 'No active professor subscriptions',
    'account.subscription.activeSubscription': 'Active subscription',
    'account.subscription.discountMessage': 'You get',
    'account.subscription.discountSuffix': 'discount on all paid programs from this professor',
    'account.subscription.discoverMore': 'Discover more professors',
    'account.subscription.subscribeBenefitsIntro': 'Subscribe to your favorite professors to:',
    'account.subscription.subscribeBenefit1': 'Access all their exclusive content (videos and programs)',
    'account.subscription.subscribeBenefit2': 'Discounts on paid programs',
    'account.subscription.subscribeBenefit3': 'Priority booking for events',
    'account.subscription.discoverProfessors': 'Discover professors',
    'account.billing.title': 'Billing Information',
    'account.billing.paymentMethod': 'Payment Method',
    'account.billing.stripeMessage': 'Connect Stripe to manage billing and payment methods',
    'account.billing.stripeRequired': 'Stripe Integration Required',
    'account.billing.history': 'Billing History',
    'account.billing.noHistory': 'No billing history available',

    'signin.header.title': 'Welcome Back',
    'signin.header.subtitle': 'Access your personal space',
    'signin.form.email': 'Email',
    'signin.form.emailPlaceholder': 'your@email.com',
    'signin.form.password': 'Password',
    'signin.form.passwordPlaceholder': 'Enter your password',
    'signin.form.signingIn': 'Signing in...',
    'signin.form.signIn': 'Sign In',
    'signin.footer.noAccount': 'Don\'t have an account?',
    'signin.footer.signUp': 'Sign up',

    'signup.header.title': 'Start Your Journey',
    'signup.header.subtitle': 'Join NEXA Universe today',
    'signup.form.fullName': 'Full Name',
    'signup.form.fullNamePlaceholder': 'Your name',
    'signup.form.email': 'Email',
    'signup.form.emailPlaceholder': 'your@email.com',
    'signup.form.password': 'Password',
    'signup.form.passwordPlaceholder': 'At least 6 characters',
    'signup.form.creating': 'Creating account...',
    'signup.form.success': 'Success!',
    'signup.form.createAccount': 'Create Account',
    'signup.form.successMessage': 'Account created successfully!',
    'signup.errors.passwordTooShort': 'Password must be at least 6 characters',
    'signup.footer.hasAccount': 'Already have an account?',
    'signup.footer.signIn': 'Sign in',

    'purchases.title': 'My Purchases',
    'purchases.subtitle': 'Manage your subscriptions and purchases',
    'purchases.platformSubscription': 'Platform Subscription',
    'purchases.status.active': 'Active',
    'purchases.status.trial': 'Trial',
    'purchases.status.inactive': 'Inactive',
    'purchases.status.cancelled': 'Cancelled',
    'purchases.status.accessible': 'Accessible',
    'purchases.status.refunded': 'Refunded',
    'purchases.status.expired': 'Expired',
    'purchases.expiresOn': 'Expires on',
    'purchases.expiresSoon': 'Your subscription expires soon',
    'purchases.since': 'Since',
    'purchases.purchasedOn': 'Purchased on',
    'purchases.viewProfile': 'View profile',
    'purchases.watch': 'Watch',
    'purchases.access': 'Access',

    'purchases.tabs.professors': 'Professors',
    'purchases.tabs.programs': 'Programs',
    'purchases.tabs.videos': 'Videos',
    'purchases.tabs.orders': 'Orders',

    'purchases.noProfessors': 'No professor subscriptions',
    'purchases.noProfessorsDesc': 'Subscribe to your favorite professors to access their exclusive content',
    'purchases.discoverProfessors': 'Discover professors',

    'purchases.noPrograms': 'No programs purchased',
    'purchases.noProgramsDesc': 'Buy complete programs to progress effectively',
    'purchases.explorePrograms': 'Explore programs',

    'purchases.noVideos': 'No videos purchased',
    'purchases.noVideosDesc': 'Buy individual videos to enrich your learning',
    'purchases.exploreAcademy': 'Explore academy',

    'purchases.noOrders': 'No orders',
    'purchases.noOrdersDesc': 'Order products from our shop',
    'purchases.visitShop': 'Visit shop',

    'purchases.order': 'Order',
    'purchases.items': 'Items',
    'purchases.memberPrice': 'Member price',
    'purchases.delivered': 'Delivered',
    'purchases.shipped': 'Shipped',
    'purchases.processing': 'Processing',
    'purchases.paid': 'Paid',
    'purchases.pending': 'Pending',

    'common.level.beginner': 'Beginner',
    'common.level.intermediate': 'Intermediate',
    'common.level.advanced': 'Advanced',
    'common.minutes': 'min',
    'common.videos': 'videos',
    'common.video': 'video',
  },
  pt: {
    'nav.academy': 'Academia',
    'nav.professors': 'Professores',
    'nav.shop': 'Loja',
    'nav.myPurchases': 'Minhas Compras',
    'nav.favorites': 'Favoritos',
    'nav.dashboard': 'Painel',
    'nav.admin': 'Admin',
    'nav.account': 'Conta',
    'nav.cart': 'Carrinho',
    'nav.signOut': 'Sair',
    'nav.signIn': 'Entrar',
    'nav.getStarted': 'Começar',

    'landing.hero.badge': 'Progrida na Dança com Professores de Classe Mundial',
    'landing.hero.titleStart': 'Sua Jornada para',
    'landing.hero.titleHighlight': 'a Excelência em Dança',
    'landing.hero.description': 'Desenvolva seu potencial com cursos em vídeo estruturados e programas adaptados a todos os níveis. Aprenda no seu ritmo, a qualquer hora, em qualquer lugar.',
    'landing.hero.ctaPrimary': 'Começar a Aprender',
    'landing.hero.ctaSecondary': 'Explorar a Academia',
    'landing.features.titleStart': 'Por que juntar-se',
    'landing.features.titleHighlight': 'NEXA UNIVERSE',
    'landing.features.subtitle': 'Transforme sua jornada de dança com nossa plataforma completa',
    'landing.features.feature1.title': 'Tudo no mesmo lugar',
    'landing.features.feature1.description': 'Cursos online, programas de professores, conteúdo exclusivo: toda sua aprendizagem está centralizada em uma única plataforma, simples e organizada. Menos dispersão. Mais progresso.',
    'landing.features.feature2.title': 'Gestão fácil de passes e eventos',
    'landing.features.feature2.description': 'Compre seus passes diretamente na plataforma e acesse-os a qualquer momento em seu espaço pessoal (QR codes, informações, histórico). Seus passes, sempre acessíveis, sempre prontos.',
    'landing.features.feature3.title': 'Loja oficial NEXA',
    'landing.features.feature3.description': 'Merch, bolsa do festivaleiro, produtos úteis para dançarinos: a loja NEXA está integrada ao aplicativo, com benefícios exclusivos para membros. Cultura da dança, até nos detalhes.',
    'landing.cta.badge': 'Oferta por Tempo Limitado',
    'landing.cta.title': 'Pronto para Começar Sua Jornada?',
    'landing.cta.description': 'Junte-se à nossa comunidade de dançarinos apaixonados e desenvolva suas habilidades hoje.',
    'landing.cta.pricePrefix': 'A partir de',
    'landing.cta.priceSuffix': '/mês',
    'landing.cta.button': 'Começar Agora',
    'landing.footer.copyright': '© 2024 NEXA UNIVERSE. Todos os direitos reservados.',

    'academy.header.title': 'Academia',
    'academy.header.accessFull': 'Acesso completo a todos os níveis',
    'academy.header.accessLimited': 'Assine para desbloquear todo o conteúdo',
    'academy.banner.title': 'NEXA UNIVERSE Access',
    'academy.banner.description': 'Crie uma conta gratuita para explorar a plataforma. Atualize para NEXA Access para desbloquear todo o conteúdo premium, descontos exclusivos e muito mais.',
    'academy.banner.pricing': 'Assinatura premium: €8.99/mês ou €89/ano',
    'academy.banner.button': 'Descobrir NEXA Access',
    'academy.filters.title': 'Busca e filtros',
    'academy.filters.searchPlaceholder': 'Buscar vídeos ou programas...',
    'academy.filters.allProfessors': 'Todos os professores',
    'academy.filters.allLevels': 'Todos',
    'academy.filters.beginner': 'Iniciante',
    'academy.filters.intermediate': 'Inter',
    'academy.filters.advanced': 'Avançado',
    'academy.filters.activeLabel': 'Filtros ativos:',
    'academy.filters.resetAll': 'Redefinir tudo',
    'academy.tabs.programs': 'Programas',
    'academy.tabs.videos': 'Vídeos',
    'academy.empty.programsFiltered': 'Nenhum programa corresponde aos seus filtros',
    'academy.empty.programsNone': 'Nenhum programa disponível no momento',
    'academy.empty.videosFiltered': 'Nenhum vídeo corresponde aos seus filtros',
    'academy.empty.videosNone': 'Nenhum vídeo disponível',
    'academy.card.locked': 'Bloqueado',
    'academy.card.accessible': 'Acessível',
    'academy.card.purchased': 'Comprado',
    'academy.card.by': 'Por',
    'academy.card.videos': 'vídeos',
    'academy.card.minutes': 'min',
    'academy.card.public': 'Público',
    'academy.card.subscribers': 'Assinantes',
    'academy.card.paid': 'Pago',
    'academy.card.free': 'Grátis',
    'academy.card.loginRequired': 'Login necessário',
    'academy.card.subscriptionRequired': 'Assinatura necessária',
    'academy.levels.beginner': 'Iniciante',
    'academy.levels.intermediate': 'Intermediário',
    'academy.levels.advanced': 'Avançado',
    'academy.levels.allLevels': 'Todos os níveis',
    'academy.modal.locked': 'Vídeo Bloqueado',
    'academy.modal.loginMessage': 'Faça login para acessar este vídeo',
    'academy.modal.login': 'Fazer Login',
    'academy.modal.subscribeProfessor': 'Assine o professor para acessar este vídeo',
    'academy.modal.viewProfessor': 'Ver perfil do professor',
    'academy.modal.subscribeNexa': 'Assine o NEXA Access para desbloquear este vídeo',
    'academy.modal.subscribeButton': 'Assinar NEXA Access',
    'academy.modal.close': 'Fechar',

    'professors.header.titleStart': 'Conheça Seus',
    'professors.header.titleHighlight': 'Instrutores',
    'professors.header.subtitle': 'Aprenda com profissionais de kizomba de classe mundial com anos de experiência em ensino',
    'professors.search.placeholder': 'Buscar professor por nome ou bio...',
    'professors.filters.allSpecialties': 'Todas as especialidades',
    'professors.filters.activeLabel': 'Filtros ativos:',
    'professors.filters.resetAll': 'Redefinir tudo',
    'professors.empty.filtered': 'Nenhum professor corresponde aos seus filtros',
    'professors.empty.none': 'Nenhum professor disponível no momento',
    'professors.card.featured': 'Instrutor Destaque',
    'professors.card.founder': 'Instrutor Fundador',
    'professors.card.experience': 'anos de experiência',
    'professors.card.noBio': 'Nenhuma biografia disponível.',
    'professors.card.watchIntro': 'Assistir Introdução',
    'professors.card.viewProfile': 'Ver Perfil e Cursos',

    'shop.header.brand': 'NEXA UNIVERSE',
    'shop.header.title': 'Loja',
    'shop.header.subtitle': 'Produtos exclusivos e passes para eventos',
    'shop.header.memberActive': 'Preço de membro ativo',
    'shop.success.addedToCart': 'adicionado ao carrinho!',
    'shop.success.viewCart': 'Ver Carrinho',
    'shop.search.placeholder': 'Buscar produtos...',
    'shop.filters.priceLabel': 'Preço:',
    'shop.filters.all': 'Todos',
    'shop.filters.under25': 'Menos de €25',
    'shop.filters.range25to50': '€25 - €50',
    'shop.filters.over50': 'Mais de €50',
    'shop.tabs.merchandise': 'Produtos',
    'shop.tabs.events': 'Eventos',
    'shop.empty.filtered': 'Nenhum produto corresponde à sua busca',
    'shop.empty.no': 'Nenhum',
    'shop.empty.product': 'produto',
    'shop.empty.event': 'evento',
    'shop.empty.available': 'disponível no momento',
    'shop.product.memberBadge': 'PREÇO DE MEMBRO',
    'shop.product.outOfStock': 'Fora de Estoque',
    'shop.product.eventPass': 'Passe de Evento',
    'shop.product.availableSizes': 'Tamanhos disponíveis:',
    'shop.product.availableCategories': 'Categorias disponíveis:',
    'shop.product.forMembers': 'para membros',
    'shop.product.addToCart': 'Adicionar ao Carrinho',
    'shop.modal.selectSize': 'Selecionar Tamanho',
    'shop.modal.selectCategory': 'Selecione uma categoria',
    'shop.modal.quantity': 'Quantidade',
    'shop.modal.cancel': 'Cancelar',

    'cart.notSignedIn.message': 'Faça login para ver seu carrinho',
    'cart.notSignedIn.button': 'Fazer Login',
    'cart.success.title': 'Pedido Realizado com Sucesso!',
    'cart.success.message': 'Obrigado pelo seu pedido. Enviaremos um e-mail de confirmação em breve.',
    'cart.success.continueShopping': 'Continuar Comprando',
    'cart.success.viewOrders': 'Ver Pedidos',
    'cart.header.your': 'Seu',
    'cart.header.cart': 'Carrinho',
    'cart.empty.title': 'Seu carrinho está vazio',
    'cart.empty.message': 'Adicione alguns itens para começar',
    'cart.empty.button': 'Ir para a Loja',
    'cart.item.category': 'Categoria',
    'cart.item.size': 'Tamanho',
    'cart.item.subtotal': 'Subtotal',
    'cart.summary.title': 'Resumo do Pedido',
    'cart.summary.subtotal': 'Subtotal',
    'cart.summary.memberSavings': 'Economia de Membro',
    'cart.summary.total': 'Total',
    'cart.summary.fullName': 'Nome Completo *',
    'cart.summary.email': 'E-mail *',
    'cart.summary.phone': 'Telefone',
    'cart.summary.shippingAddress': 'Endereço de Entrega *',
    'cart.summary.orderNotes': 'Notas do pedido (opcional)',
    'cart.summary.processing': 'Processando...',
    'cart.summary.placeOrder': 'Fazer Pedido',
    'cart.summary.manualNote': 'Seu pedido será processado manualmente. Entraremos em contato para os detalhes de pagamento.',
    'cart.errors.empty': 'Seu carrinho está vazio',
    'cart.errors.shippingRequired': 'Por favor, preencha todas as informações de entrega',

    'favorites.header.my': 'Meus',
    'favorites.header.favorites': 'Favoritos',
    'favorites.header.savedSingular': 'favorito salvo',
    'favorites.header.savedPlural': 'favoritos salvos',
    'favorites.tabs.all': 'Todos',
    'favorites.tabs.professors': 'Professores',
    'favorites.tabs.videos': 'Vídeos',
    'favorites.tabs.programs': 'Programas',
    'favorites.empty.title': 'Nenhum favorito',
    'favorites.empty.message': 'Comece adicionando professores, vídeos e programas aos seus favoritos',
    'favorites.empty.button': 'Explorar a Academia',
    'favorites.sections.professors': 'Professores',
    'favorites.sections.videos': 'Vídeos',
    'favorites.sections.programs': 'Programas',
    'favorites.cards.viewProfile': 'Ver perfil',
    'favorites.cards.removeTitle': 'Remover dos favoritos',
    'favorites.cards.watch': 'Assistir',
    'favorites.cards.viewProgram': 'Ver programa',
    'favorites.cards.videos': 'vídeos',

    'account.header.title': 'Configurações da Conta',
    'account.tabs.profile': 'Perfil',
    'account.tabs.subscription': 'Assinatura',
    'account.tabs.billing': 'Faturamento',
    'account.profile.title': 'Informações do Perfil',
    'account.profile.email': 'E-mail',
    'account.profile.fullName': 'Nome Completo',
    'account.profile.role': 'Função',
    'account.profile.errorUpdate': 'Erro ao atualizar perfil',
    'account.profile.successUpdate': 'Perfil atualizado com sucesso',
    'account.profile.saving': 'Salvando...',
    'account.profile.saveButton': 'Salvar Alterações',
    'account.subscription.title': 'Minhas Assinaturas',
    'account.subscription.platformTitle': 'Assinatura da Plataforma',
    'account.subscription.active': 'Ativo',
    'account.subscription.inactive': 'Inativo',
    'account.subscription.expiresOn': 'Expira em',
    'account.subscription.benefit1': 'Acesso aos vídeos de propriedade da plataforma',
    'account.subscription.benefit2': 'Desconto na loja',
    'account.subscription.benefit3': 'Desconto em passes de eventos parceiros',
    'account.subscription.platformRequired': 'A assinatura da plataforma é necessária para acessar a academia e assinar professores.',
    'account.subscription.modal.chooseYourPlan': 'Escolha sua assinatura',
    'account.subscription.modal.accessAllPremium': 'Acesse todo o conteúdo premium da plataforma',
    'account.subscription.modal.monthly': 'Mensal',
    'account.subscription.modal.flexibleCommitment': 'Compromisso flexível',
    'account.subscription.modal.perMonth': '/mês',
    'account.subscription.modal.annual': 'Anual',
    'account.subscription.modal.bestOffer': 'Melhor oferta',
    'account.subscription.modal.perYear': '/ano',
    'account.subscription.modal.orPerMonth': 'Ou {price}€/mês',
    'account.subscription.modal.savePercent': 'ECONOMIZE {percent}%',
    'account.subscription.modal.chooseMonthly': 'Escolher Mensal',
    'account.subscription.modal.chooseAnnual': 'Escolher Anual',
    'account.subscription.modal.securePayment': 'Pagamento seguro pelo Stripe • Cancele a qualquer momento',
    'account.subscription.modal.benefit1': 'Acesso aos vídeos de propriedade da plataforma',
    'account.subscription.modal.benefit2': 'Desconto na loja',
    'account.subscription.modal.benefit3': 'Desconto em passes de eventos parceiros',
    'account.subscription.professorsTitle': 'Assinaturas de Professores',
    'account.subscription.subscribedTo': 'Você está inscrito em',
    'account.subscription.professorSingular': 'professor',
    'account.subscription.professorPlural': 'professores',
    'account.subscription.noProfessors': 'Nenhuma assinatura de professor ativa',
    'account.subscription.activeSubscription': 'Assinatura ativa',
    'account.subscription.discountMessage': 'Você recebe',
    'account.subscription.discountSuffix': 'de desconto em todos os programas pagos deste professor',
    'account.subscription.discoverMore': 'Descobrir mais professores',
    'account.subscription.subscribeBenefitsIntro': 'Assine seus professores favoritos para:',
    'account.subscription.subscribeBenefit1': 'Acessar todo o conteúdo exclusivo deles (vídeos e programas)',
    'account.subscription.subscribeBenefit2': 'Descontos em programas pagos',
    'account.subscription.subscribeBenefit3': 'Prioridade de reserva para eventos',
    'account.subscription.discoverProfessors': 'Descobrir professores',
    'account.billing.title': 'Informações de Faturamento',
    'account.billing.paymentMethod': 'Método de Pagamento',
    'account.billing.stripeMessage': 'Conecte o Stripe para gerenciar faturamento e métodos de pagamento',
    'account.billing.stripeRequired': 'Integração com Stripe Necessária',
    'account.billing.history': 'Histórico de Faturamento',
    'account.billing.noHistory': 'Nenhum histórico de faturamento disponível',

    'signin.header.title': 'Bem-Vindo de Volta',
    'signin.header.subtitle': 'Acesse seu espaço pessoal',
    'signin.form.email': 'E-mail',
    'signin.form.emailPlaceholder': 'seu@email.com',
    'signin.form.password': 'Senha',
    'signin.form.passwordPlaceholder': 'Digite sua senha',
    'signin.form.signingIn': 'Entrando...',
    'signin.form.signIn': 'Entrar',
    'signin.footer.noAccount': 'Não tem uma conta?',
    'signin.footer.signUp': 'Criar conta',

    'signup.header.title': 'Comece Sua Jornada',
    'signup.header.subtitle': 'Junte-se ao NEXA Universe hoje',
    'signup.form.fullName': 'Nome Completo',
    'signup.form.fullNamePlaceholder': 'Seu nome',
    'signup.form.email': 'E-mail',
    'signup.form.emailPlaceholder': 'seu@email.com',
    'signup.form.password': 'Senha',
    'signup.form.passwordPlaceholder': 'Pelo menos 6 caracteres',
    'signup.form.creating': 'Criando conta...',
    'signup.form.success': 'Sucesso!',
    'signup.form.createAccount': 'Criar Conta',
    'signup.form.successMessage': 'Conta criada com sucesso!',
    'signup.errors.passwordTooShort': 'A senha deve ter pelo menos 6 caracteres',
    'signup.footer.hasAccount': 'Já tem uma conta?',
    'signup.footer.signIn': 'Entrar',

    'purchases.title': 'Minhas Compras',
    'purchases.subtitle': 'Gerencie suas assinaturas e compras',
    'purchases.platformSubscription': 'Assinatura da Plataforma',
    'purchases.status.active': 'Ativo',
    'purchases.status.trial': 'Teste',
    'purchases.status.inactive': 'Inativo',
    'purchases.status.cancelled': 'Cancelado',
    'purchases.status.accessible': 'Acessível',
    'purchases.status.refunded': 'Reembolsado',
    'purchases.status.expired': 'Expirado',
    'purchases.expiresOn': 'Expira em',
    'purchases.expiresSoon': 'Sua assinatura expira em breve',
    'purchases.since': 'Desde',
    'purchases.purchasedOn': 'Comprado em',
    'purchases.viewProfile': 'Ver perfil',
    'purchases.watch': 'Assistir',
    'purchases.access': 'Acessar',

    'purchases.tabs.professors': 'Professores',
    'purchases.tabs.programs': 'Programas',
    'purchases.tabs.videos': 'Vídeos',
    'purchases.tabs.orders': 'Pedidos',

    'purchases.noProfessors': 'Nenhuma assinatura de professor',
    'purchases.noProfessorsDesc': 'Assine seus professores favoritos para acessar seu conteúdo exclusivo',
    'purchases.discoverProfessors': 'Descobrir professores',

    'purchases.noPrograms': 'Nenhum programa comprado',
    'purchases.noProgramsDesc': 'Compre programas completos para progredir efetivamente',
    'purchases.explorePrograms': 'Explorar programas',

    'purchases.noVideos': 'Nenhum vídeo comprado',
    'purchases.noVideosDesc': 'Compre vídeos individuais para enriquecer seu aprendizado',
    'purchases.exploreAcademy': 'Explorar academia',

    'purchases.noOrders': 'Nenhum pedido',
    'purchases.noOrdersDesc': 'Peça produtos em nossa loja',
    'purchases.visitShop': 'Visitar loja',

    'purchases.order': 'Pedido',
    'purchases.items': 'Itens',
    'purchases.memberPrice': 'Preço de membro',
    'purchases.delivered': 'Entregue',
    'purchases.shipped': 'Enviado',
    'purchases.processing': 'Processando',
    'purchases.paid': 'Pago',
    'purchases.pending': 'Pendente',

    'common.level.beginner': 'Iniciante',
    'common.level.intermediate': 'Intermediário',
    'common.level.advanced': 'Avançado',
    'common.minutes': 'min',
    'common.videos': 'vídeos',
    'common.video': 'vídeo',
  },
  es: {
    'nav.academy': 'Academia',
    'nav.professors': 'Profesores',
    'nav.shop': 'Tienda',
    'nav.myPurchases': 'Mis Compras',
    'nav.favorites': 'Favoritos',
    'nav.dashboard': 'Panel',
    'nav.admin': 'Admin',
    'nav.account': 'Cuenta',
    'nav.cart': 'Carrito',
    'nav.signOut': 'Cerrar Sesión',
    'nav.signIn': 'Iniciar Sesión',
    'nav.getStarted': 'Comenzar',

    'landing.hero.badge': 'Progresa en la Danza con Profesores de Clase Mundial',
    'landing.hero.titleStart': 'Tu Viaje hacia',
    'landing.hero.titleHighlight': 'la Excelencia en Danza',
    'landing.hero.description': 'Desarrolla tu potencial con cursos en vídeo estructurados y programas adaptados a todos los niveles. Aprende a tu ritmo, en cualquier momento, en cualquier lugar.',
    'landing.hero.ctaPrimary': 'Comenzar a Aprender',
    'landing.hero.ctaSecondary': 'Explorar la Academia',
    'landing.features.titleStart': 'Por qué unirse a',
    'landing.features.titleHighlight': 'NEXA UNIVERSE',
    'landing.features.subtitle': 'Transforma tu viaje de baile con nuestra plataforma completa',
    'landing.features.feature1.title': 'Todo en un mismo lugar',
    'landing.features.feature1.description': 'Cursos en línea, programas de profesores, contenido exclusivo: todo tu aprendizaje está centralizado en una única plataforma, simple y organizada. Menos dispersión. Más progreso.',
    'landing.features.feature2.title': 'Gestión fácil de pases y eventos',
    'landing.features.feature2.description': 'Compra tus pases directamente en la plataforma y accede a ellos en cualquier momento en tu espacio personal (códigos QR, información, historial). Tus pases, siempre accesibles, siempre listos.',
    'landing.features.feature3.title': 'Tienda oficial NEXA',
    'landing.features.feature3.description': 'Merch, bolsa del festivalero, productos útiles para bailarines: la tienda NEXA está integrada en la aplicación, con beneficios exclusivos para miembros. Cultura de baile, hasta en los detalles.',
    'landing.cta.badge': 'Oferta por Tiempo Limitado',
    'landing.cta.title': '¿Listo para Comenzar Tu Viaje?',
    'landing.cta.description': 'Únete a nuestra comunidad de bailarines apasionados y desarrolla tus habilidades hoy.',
    'landing.cta.pricePrefix': 'Desde solo',
    'landing.cta.priceSuffix': '/mes',
    'landing.cta.button': 'Comenzar Ahora',
    'landing.footer.copyright': '© 2024 NEXA UNIVERSE. Todos los derechos reservados.',

    'academy.header.title': 'Academia',
    'academy.header.accessFull': 'Acceso completo a todos los niveles',
    'academy.header.accessLimited': 'Suscríbete para desbloquear todo el contenido',
    'academy.banner.title': 'NEXA UNIVERSE Access',
    'academy.banner.description': 'Crea una cuenta gratuita para explorar la plataforma. Actualiza a NEXA Access para desbloquear todo el contenido premium, descuentos exclusivos y mucho más.',
    'academy.banner.pricing': 'Suscripción premium: €8.99/mes o €89/año',
    'academy.banner.button': 'Descubrir NEXA Access',
    'academy.filters.title': 'Búsqueda y filtros',
    'academy.filters.searchPlaceholder': 'Buscar vídeos o programas...',
    'academy.filters.allProfessors': 'Todos los profesores',
    'academy.filters.allLevels': 'Todos',
    'academy.filters.beginner': 'Principiante',
    'academy.filters.intermediate': 'Inter',
    'academy.filters.advanced': 'Avanzado',
    'academy.filters.activeLabel': 'Filtros activos:',
    'academy.filters.resetAll': 'Restablecer todo',
    'academy.tabs.programs': 'Programas',
    'academy.tabs.videos': 'Vídeos',
    'academy.empty.programsFiltered': 'Ningún programa coincide con tus filtros',
    'academy.empty.programsNone': 'No hay programas disponibles en este momento',
    'academy.empty.videosFiltered': 'Ningún vídeo coincide con tus filtros',
    'academy.empty.videosNone': 'No hay vídeos disponibles',
    'academy.card.locked': 'Bloqueado',
    'academy.card.accessible': 'Accesible',
    'academy.card.purchased': 'Comprado',
    'academy.card.by': 'Por',
    'academy.card.videos': 'vídeos',
    'academy.card.minutes': 'min',
    'academy.card.public': 'Público',
    'academy.card.subscribers': 'Suscriptores',
    'academy.card.paid': 'De pago',
    'academy.card.free': 'Gratis',
    'academy.card.loginRequired': 'Inicio de sesión requerido',
    'academy.card.subscriptionRequired': 'Suscripción requerida',
    'academy.levels.beginner': 'Principiante',
    'academy.levels.intermediate': 'Intermedio',
    'academy.levels.advanced': 'Avanzado',
    'academy.levels.allLevels': 'Todos los niveles',
    'academy.modal.locked': 'Vídeo Bloqueado',
    'academy.modal.loginMessage': 'Inicia sesión para acceder a este vídeo',
    'academy.modal.login': 'Iniciar Sesión',
    'academy.modal.subscribeProfessor': 'Suscríbete al profesor para acceder a este vídeo',
    'academy.modal.viewProfessor': 'Ver perfil del profesor',
    'academy.modal.subscribeNexa': 'Suscríbete a NEXA Access para desbloquear este vídeo',
    'academy.modal.subscribeButton': 'Suscribirse a NEXA Access',
    'academy.modal.close': 'Cerrar',

    'professors.header.titleStart': 'Conoce a Tus',
    'professors.header.titleHighlight': 'Instructores',
    'professors.header.subtitle': 'Aprende de profesionales de kizomba de clase mundial con años de experiencia docente',
    'professors.search.placeholder': 'Buscar profesor por nombre o biografía...',
    'professors.filters.allSpecialties': 'Todas las especialidades',
    'professors.filters.activeLabel': 'Filtros activos:',
    'professors.filters.resetAll': 'Restablecer todo',
    'professors.empty.filtered': 'Ningún profesor coincide con tus filtros',
    'professors.empty.none': 'No hay profesores disponibles en este momento',
    'professors.card.featured': 'Instructor Destacado',
    'professors.card.founder': 'Instructor Fundador',
    'professors.card.experience': 'años de experiencia',
    'professors.card.noBio': 'No hay biografía disponible.',
    'professors.card.watchIntro': 'Ver Introducción',
    'professors.card.viewProfile': 'Ver Perfil y Cursos',

    'shop.header.brand': 'NEXA UNIVERSE',
    'shop.header.title': 'Tienda',
    'shop.header.subtitle': 'Productos exclusivos y pases para eventos',
    'shop.header.memberActive': 'Precio de miembro activo',
    'shop.success.addedToCart': 'añadido al carrito!',
    'shop.success.viewCart': 'Ver Carrito',
    'shop.search.placeholder': 'Buscar productos...',
    'shop.filters.priceLabel': 'Precio:',
    'shop.filters.all': 'Todos',
    'shop.filters.under25': 'Menos de €25',
    'shop.filters.range25to50': '€25 - €50',
    'shop.filters.over50': 'Más de €50',
    'shop.tabs.merchandise': 'Productos',
    'shop.tabs.events': 'Eventos',
    'shop.empty.filtered': 'Ningún producto coincide con tu búsqueda',
    'shop.empty.no': 'No hay',
    'shop.empty.product': 'producto',
    'shop.empty.event': 'evento',
    'shop.empty.available': 'disponible en este momento',
    'shop.product.memberBadge': 'PRECIO DE MIEMBRO',
    'shop.product.outOfStock': 'Agotado',
    'shop.product.eventPass': 'Pase de Evento',
    'shop.product.availableSizes': 'Tallas disponibles:',
    'shop.product.availableCategories': 'Categorías disponibles:',
    'shop.product.forMembers': 'para miembros',
    'shop.product.addToCart': 'Añadir al Carrito',
    'shop.modal.selectSize': 'Seleccionar Talla',
    'shop.modal.selectCategory': 'Selecciona una categoría',
    'shop.modal.quantity': 'Cantidad',
    'shop.modal.cancel': 'Cancelar',

    'cart.notSignedIn.message': 'Inicia sesión para ver tu carrito',
    'cart.notSignedIn.button': 'Iniciar Sesión',
    'cart.success.title': '¡Pedido Realizado con Éxito!',
    'cart.success.message': 'Gracias por tu pedido. Te enviaremos un correo de confirmación en breve.',
    'cart.success.continueShopping': 'Continuar Comprando',
    'cart.success.viewOrders': 'Ver Pedidos',
    'cart.header.your': 'Tu',
    'cart.header.cart': 'Carrito',
    'cart.empty.title': 'Tu carrito está vacío',
    'cart.empty.message': 'Añade algunos artículos para comenzar',
    'cart.empty.button': 'Ir a la Tienda',
    'cart.item.category': 'Categoría',
    'cart.item.size': 'Talla',
    'cart.item.subtotal': 'Subtotal',
    'cart.summary.title': 'Resumen del Pedido',
    'cart.summary.subtotal': 'Subtotal',
    'cart.summary.memberSavings': 'Ahorro de Miembro',
    'cart.summary.total': 'Total',
    'cart.summary.fullName': 'Nombre Completo *',
    'cart.summary.email': 'Correo Electrónico *',
    'cart.summary.phone': 'Teléfono',
    'cart.summary.shippingAddress': 'Dirección de Envío *',
    'cart.summary.orderNotes': 'Notas del pedido (opcional)',
    'cart.summary.processing': 'Procesando...',
    'cart.summary.placeOrder': 'Realizar Pedido',
    'cart.summary.manualNote': 'Tu pedido será procesado manualmente. Te contactaremos para los detalles de pago.',
    'cart.errors.empty': 'Tu carrito está vacío',
    'cart.errors.shippingRequired': 'Por favor, completa toda la información de envío',

    'favorites.header.my': 'Mis',
    'favorites.header.favorites': 'Favoritos',
    'favorites.header.savedSingular': 'favorito guardado',
    'favorites.header.savedPlural': 'favoritos guardados',
    'favorites.tabs.all': 'Todos',
    'favorites.tabs.professors': 'Profesores',
    'favorites.tabs.videos': 'Vídeos',
    'favorites.tabs.programs': 'Programas',
    'favorites.empty.title': 'Sin favoritos',
    'favorites.empty.message': 'Comienza añadiendo profesores, vídeos y programas a tus favoritos',
    'favorites.empty.button': 'Explorar la Academia',
    'favorites.sections.professors': 'Profesores',
    'favorites.sections.videos': 'Vídeos',
    'favorites.sections.programs': 'Programas',
    'favorites.cards.viewProfile': 'Ver perfil',
    'favorites.cards.removeTitle': 'Quitar de favoritos',
    'favorites.cards.watch': 'Ver',
    'favorites.cards.viewProgram': 'Ver programa',
    'favorites.cards.videos': 'vídeos',

    'account.header.title': 'Configuración de la Cuenta',
    'account.tabs.profile': 'Perfil',
    'account.tabs.subscription': 'Suscripción',
    'account.tabs.billing': 'Facturación',
    'account.profile.title': 'Información del Perfil',
    'account.profile.email': 'Correo Electrónico',
    'account.profile.fullName': 'Nombre Completo',
    'account.profile.role': 'Rol',
    'account.profile.errorUpdate': 'Error al actualizar el perfil',
    'account.profile.successUpdate': 'Perfil actualizado con éxito',
    'account.profile.saving': 'Guardando...',
    'account.profile.saveButton': 'Guardar Cambios',
    'account.subscription.title': 'Mis Suscripciones',
    'account.subscription.platformTitle': 'Suscripción de Plataforma',
    'account.subscription.active': 'Activo',
    'account.subscription.inactive': 'Inactivo',
    'account.subscription.expiresOn': 'Expira el',
    'account.subscription.benefit1': 'Acceso a los vídeos de propiedad de la plataforma',
    'account.subscription.benefit2': 'Descuento en la tienda',
    'account.subscription.benefit3': 'Descuento en pases de eventos asociados',
    'account.subscription.platformRequired': 'La suscripción de plataforma es necesaria para acceder a la academia y suscribirse a profesores.',
    'account.subscription.modal.chooseYourPlan': 'Elige tu suscripción',
    'account.subscription.modal.accessAllPremium': 'Accede a todo el contenido premium de la plataforma',
    'account.subscription.modal.monthly': 'Mensual',
    'account.subscription.modal.flexibleCommitment': 'Compromiso flexible',
    'account.subscription.modal.perMonth': '/mes',
    'account.subscription.modal.annual': 'Anual',
    'account.subscription.modal.bestOffer': 'Mejor oferta',
    'account.subscription.modal.perYear': '/año',
    'account.subscription.modal.orPerMonth': 'O {price}€/mes',
    'account.subscription.modal.savePercent': 'AHORRA {percent}%',
    'account.subscription.modal.chooseMonthly': 'Elegir Mensual',
    'account.subscription.modal.chooseAnnual': 'Elegir Anual',
    'account.subscription.modal.securePayment': 'Pago seguro por Stripe • Cancela en cualquier momento',
    'account.subscription.modal.benefit1': 'Acceso a los vídeos de propiedad de la plataforma',
    'account.subscription.modal.benefit2': 'Descuento en la tienda',
    'account.subscription.modal.benefit3': 'Descuento en pases de eventos asociados',
    'account.subscription.professorsTitle': 'Suscripciones de Profesores',
    'account.subscription.subscribedTo': 'Estás suscrito a',
    'account.subscription.professorSingular': 'profesor',
    'account.subscription.professorPlural': 'profesores',
    'account.subscription.noProfessors': 'Sin suscripciones de profesores activas',
    'account.subscription.activeSubscription': 'Suscripción activa',
    'account.subscription.discountMessage': 'Obtienes',
    'account.subscription.discountSuffix': 'de descuento en todos los programas de pago de este profesor',
    'account.subscription.discoverMore': 'Descubrir más profesores',
    'account.subscription.subscribeBenefitsIntro': 'Suscríbete a tus profesores favoritos para:',
    'account.subscription.subscribeBenefit1': 'Acceder a todo su contenido exclusivo (vídeos y programas)',
    'account.subscription.subscribeBenefit2': 'Descuentos en programas de pago',
    'account.subscription.subscribeBenefit3': 'Prioridad de reserva para eventos',
    'account.subscription.discoverProfessors': 'Descubrir profesores',
    'account.billing.title': 'Información de Facturación',
    'account.billing.paymentMethod': 'Método de Pago',
    'account.billing.stripeMessage': 'Conecta Stripe para gestionar facturación y métodos de pago',
    'account.billing.stripeRequired': 'Integración con Stripe Necesaria',
    'account.billing.history': 'Historial de Facturación',
    'account.billing.noHistory': 'No hay historial de facturación disponible',

    'signin.header.title': 'Bienvenido de Nuevo',
    'signin.header.subtitle': 'Accede a tu espacio personal',
    'signin.form.email': 'Correo Electrónico',
    'signin.form.emailPlaceholder': 'tu@email.com',
    'signin.form.password': 'Contraseña',
    'signin.form.passwordPlaceholder': 'Ingresa tu contraseña',
    'signin.form.signingIn': 'Iniciando sesión...',
    'signin.form.signIn': 'Iniciar Sesión',
    'signin.footer.noAccount': '¿No tienes una cuenta?',
    'signin.footer.signUp': 'Crear cuenta',

    'signup.header.title': 'Comienza Tu Viaje',
    'signup.header.subtitle': 'Únete a NEXA Universe hoy',
    'signup.form.fullName': 'Nombre Completo',
    'signup.form.fullNamePlaceholder': 'Tu nombre',
    'signup.form.email': 'Correo Electrónico',
    'signup.form.emailPlaceholder': 'tu@email.com',
    'signup.form.password': 'Contraseña',
    'signup.form.passwordPlaceholder': 'Al menos 6 caracteres',
    'signup.form.creating': 'Creando cuenta...',
    'signup.form.success': '¡Éxito!',
    'signup.form.createAccount': 'Crear Cuenta',
    'signup.form.successMessage': '¡Cuenta creada con éxito!',
    'signup.errors.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'signup.footer.hasAccount': '¿Ya tienes una cuenta?',
    'signup.footer.signIn': 'Iniciar sesión',

    'purchases.title': 'Mis Compras',
    'purchases.subtitle': 'Gestiona tus suscripciones y compras',
    'purchases.platformSubscription': 'Suscripción Plataforma',
    'purchases.status.active': 'Activo',
    'purchases.status.trial': 'Prueba',
    'purchases.status.inactive': 'Inactivo',
    'purchases.status.cancelled': 'Cancelado',
    'purchases.status.accessible': 'Accesible',
    'purchases.status.refunded': 'Reembolsado',
    'purchases.status.expired': 'Expirado',
    'purchases.expiresOn': 'Expira el',
    'purchases.expiresSoon': 'Tu suscripción expira pronto',
    'purchases.since': 'Desde el',
    'purchases.purchasedOn': 'Comprado el',
    'purchases.viewProfile': 'Ver perfil',
    'purchases.watch': 'Ver',
    'purchases.access': 'Acceder',

    'purchases.tabs.professors': 'Profesores',
    'purchases.tabs.programs': 'Programas',
    'purchases.tabs.videos': 'Vídeos',
    'purchases.tabs.orders': 'Pedidos',

    'purchases.noProfessors': 'Sin suscripciones de profesores',
    'purchases.noProfessorsDesc': 'Suscríbete a tus profesores favoritos para acceder a su contenido exclusivo',
    'purchases.discoverProfessors': 'Descubrir profesores',

    'purchases.noPrograms': 'Sin programas comprados',
    'purchases.noProgramsDesc': 'Compra programas completos para progresar eficazmente',
    'purchases.explorePrograms': 'Explorar programas',

    'purchases.noVideos': 'Sin vídeos comprados',
    'purchases.noVideosDesc': 'Compra vídeos individuales para enriquecer tu aprendizaje',
    'purchases.exploreAcademy': 'Explorar academia',

    'purchases.noOrders': 'Sin pedidos',
    'purchases.noOrdersDesc': 'Pide productos en nuestra tienda',
    'purchases.visitShop': 'Visitar tienda',

    'purchases.order': 'Pedido',
    'purchases.items': 'Artículos',
    'purchases.memberPrice': 'Precio miembro',
    'purchases.delivered': 'Entregado',
    'purchases.shipped': 'Enviado',
    'purchases.processing': 'Procesando',
    'purchases.paid': 'Pagado',
    'purchases.pending': 'Pendiente',

    'common.level.beginner': 'Principiante',
    'common.level.intermediate': 'Intermedio',
    'common.level.advanced': 'Avanzado',
    'common.minutes': 'min',
    'common.videos': 'vídeos',
    'common.video': 'vídeo',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let text = translations[language][key] || key;

    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(new RegExp(`{{${param}}}`, 'g'), params[param]);
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
